spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:h2:file:./data/ecommerce
    username:
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  upload:
    dir: ${user.dir}/uploads

server:
  servlet:
    session:
      tracking-modes: cookie

